defaults:
  client: Dalli::Client
  ttl: 1800
  readonly: false
  urlencode: false
  c_threshold: 10000
  compression: true
  debug: false
  namespace: app
  sessions: false
  memory: 64
  servers: localhost:11211
  benchmarking: true
  raise_errors: true
  fast_hash: false
  fastest_hash: false

development:
  sessions: false
  fragments: false
  servers: localhost:11211

# turn off caching
test:
  disabled: true

production:
  memory: 256
  benchmarking: false
